# Generated by Django 4.2.1 on 2023-05-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('login_id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='사용자 아이디')),
                ('username', models.CharField(max_length=100, verbose_name='사용자 이름')),
                ('password', models.CharField(max_length=100, verbose_name='비밀번호')),
                ('email', models.EmailField(max_length=30, verbose_name='이메일')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='슈퍼유저 여부')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 여부')),
                ('is_staff', models.BooleanField(default=False, verbose_name='스테프 여부')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='회원가입 시기')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='업데이트 시기')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
