# Generated by Django 4.2.1 on 2023-05-24 18:26

from django.db import migrations, models
import tag.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('to_date', models.DateField()),
                ('content', models.TextField()),
                ('status', models.CharField(max_length=2)),
                ('tag_image', models.ImageField(upload_to=tag.models.image_upload_path)),
            ],
            options={
                'db_table': 'tag',
            },
        ),
    ]
